# Generated by Django 5.1.2 on 2024-10-14 06:40

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_crewmember_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewmember",
            name="image",
            field=models.ImageField(null=True, upload_to=station.models.get_image_path),
        ),
    ]
