# Generated by Django 5.1.2 on 2024-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0005_crewmember_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique_coordinates"
            ),
        ),
    ]
