# Generated by Django 5.1.2 on 2024-10-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_alter_route_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('name',)},
        ),
    ]
