# Generated by Django 5.1.2 on 2024-10-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0008_alter_station_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewmember',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='traintype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('id',)},
        ),
    ]
