# Generated by Django 5.1.2 on 2024-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("station", "0004_crewmember_trip"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="seat",
            new_name="place",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("car", "place", "trip"), name="unique_ticket"
            ),
        ),
    ]
